### ISSUE TITLE
Task list for tools/deploy.

### ISSUE THREAD

**Issue by aero31aero** [zulip/python-zulip-api#338]
This issue tracks the initial tasks with the tools/deploy script, of which some would tie in to adding further functionality to the server. `tools/deploy` itself is stable, however the corresponding server is being worked on right now and is pretty buggy. Usage instructions are on #337 right now. 

- [ ] Annotate `tools/deploy` using mypy.
- [ ] Document `tools/deploy` usage. This should be done once the system is stable enough for public usage.
- [ ] Add `tools/deploy delete` to cleanly stop and delete the docker container and image, as well as the source files for the image.
- [ ] Add `tools/deploy log <bot-name>` to show the log of the bot.
- [ ] Add `tools/deploy ls` to show a overall status (names, running/stopped) of a user's bots.

**Comment by aero31aero** [comment]
Better instructions:
https://gist.github.com/aero31aero/4a9e43641f047d983adb1e9a18e12f01

These should be used to prepare the final docs for the tools/deploy script.
